---

# The deploy script is creating a role, but doesn't specify the namespace. We need this here to make sure the context is correct before running deploy.
- shell: "oc project {{ che_namespace }}"

- name: Copy CodeReady CR file
  template: 
    src: che-cluster-cr.yaml.j2
    dest: /tmp/che-cluster-cr.yaml

- name: Extract CodeReady CLI version 2.0.0 to the temp directory
  unarchive:
    src: crwctl.tar.gz
    dest: /tmp

- set_fact:
    crwctl_install_params: ""

- set_fact:
    crwctl_install_params: "--multiuser"
  when: che_multiuser
    

- name: Run the CodeReady CLI Install command
  shell: /tmp/crwctl/bin/crwctl server:start -n {{ che_namespace }} --installer=operator --platform=openshift --che-operator-cr-yaml=/tmp/che-cluster-cr.yaml --domain={{ che_route_suffix }} {{ crwctl_install_params }}

- name: Remove the temp file
  file:
    path: /tmp/che-cluster-cr.yaml
    state: absent

- name: Remove the temp directory
  file:
    path: /tmp/crwctl
    state: absent

- import_tasks: heimdall.yml
