---
- hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: openshift
        tasks_from: set_master_vars
      when: run_master_tasks | default(true) | bool

    - name: Remove CORS entry from OpenShift master config
      include_role:
        name: mdc
        tasks_from: uninstall-cors
      tags: ['mdc']
      when: run_master_tasks | default(true) | bool
    - name: Restart openshift master services
      shell: "/usr/local/bin/master-restart {{ item }}"
      become: yes
      with_items:
        - api
        - controllers
      when: run_master_tasks | default(true) | bool
    - name: Check if openshift master services are running
      shell: oc get nodes
      register: task_result
      until: task_result.rc == 0
      retries: 6
      delay: 5
      failed_when: task_result.rc != 0
      when: run_master_tasks | default(true) | bool


# Required for Ansible Tower installs that need to login via oc as a prerequisite
- import_playbook: "../openshift.yml"
- import_playbook: "../install_heimdall.yml"

- hosts: localhost
  gather_facts: yes
  tasks:
    - include_role:
        name: prerequisites
        tasks_from: upgrade
      vars:
        from_versions:
          - "release-1.5.2"
    - set_fact:
        upgrade_webapp_image: quay.io/integreatly/tutorial-web-app:{{ webapp_version }}
        upgrade_webapp_operator_image: quay.io/integreatly/tutorial-web-app-operator:{{ webapp_operator_release_tag }}
        upgrade_fuse_image_tag: 1.7

    # Mobile Developer Console
    - name: Uninstall Mobile Developer Console
      block:
        - name: Get User RHSSO deployment desired replicas
          shell: "oc get deployment/keycloak-operator -o jsonpath='{.spec.replicas}' -n {{ eval_user_rhsso_namespace }}"
          register: expected_sso_operator_replicas
        - name: Scale down User RH-SSO
          shell: "oc scale --replicas=0 deployment/keycloak-operator -n {{ eval_user_rhsso_namespace }}"

        - name: Scale down UPS
          shell: "oc scale --replicas=0 deployment/unifiedpush-operator -n {{ eval_ups_namespace }}"

        - name: Wait for User RH-SSO operator down
          shell: "oc get po -l 'name=keycloak-operator' --no-headers -o name -n {{ eval_user_rhsso_namespace }} | wc -l"
          register: result
          until: result.stdout == "0"
          retries: 50
          delay: 10
          changed_when: False
        - name: Wait for UPS operator down
          shell: "oc get po -l 'name=unifiedpush-operator' --no-headers -o name -n {{ eval_ups_namespace }} | wc -l"
          register: result
          until: result.stdout == "0"
          retries: 50
          delay: 10
          changed_when: False

        - name: Remove MDC namespace from User RH-SSO list
          shell: "oc set env deployment/keycloak-operator 'CONSUMER_NAMESPACES={{ eval_user_rhsso_namespace }}' -n {{ eval_user_rhsso_namespace }}"
        - name: Remove MDC namespace from UPS list
          shell: "oc set env deployment/unifiedpush-operator 'APP_NAMESPACES={{ eval_ups_namespace }}' -n {{ eval_ups_namespace }}"

        - name: Get MDC ServiceInstances
          shell: "oc get serviceinstances --all-namespaces -o custom-columns='NS:.metadata.namespace,NAME:.metadata.name,CLASS:.spec.clusterServiceClassRef.name' | grep mdc-service-id | awk '{ print $1, $2 }'"
          register: mdc_serviceinstances

        - name: Delete MDC ServiceInstances
          shell:  "oc delete serviceinstance {{ item.split(' ')[1] }} -n {{ item.split(' ')[0] }}"
          loop: "{{ mdc_serviceinstances.stdout_lines }}"

        - name: Run MDC uninstall role
          include_role:
            name: mdc
            tasks_from: uninstall.yml
          vars:
            mdc_namespace: "{{ eval_mdc_namespace }}"

        - name: Scale up User RH-SSO
          shell: "oc scale --replicas={{ expected_sso_operator_replicas.stdout }} deployment/keycloak-operator -n {{ eval_user_rhsso_namespace }}"
        - name: Scale up UPS
          shell: "oc scale --replicas=1 deployment/unifiedpush-operator -n {{ eval_ups_namespace }}"

        - name: Wait for User RHSSO operator up
          shell: "oc get deployment/keycloak-operator -o jsonpath='{.status.availableReplicas}' -n {{ eval_user_rhsso_namespace }}"
          register: result
          until: result.stdout == expected_sso_operator_replicas.stdout
          retries: 50
          delay: 10
          changed_when: False

        - name: Wait for UPS operator up
          shell: "oc get deployment/unifiedpush-operator -o jsonpath='{.status.availableReplicas}' -n {{ eval_ups_namespace }}"
          register: result
          until: result.stdout == "1"
          retries: 50
          delay: 10
          changed_when: False

    # Mobile Security Service
    - name: Uninstall Mobile Security Service
      include_role:
        name: mobile_security_service
        tasks_from: uninstall_mss.yml
      vars:
        mss_namespace: "{{ eval_mobile_security_service_namespace }}"

    # UnifiedPush Server
    - name: Upgrade UnifiedPush Server operator
      include_role:
        name: ups
        tasks_from: operator_upgrade_0.2.0_0.4.0.yaml

    # Managed Service Broker
    - name: Expose vars
      include_vars: "../../roles/rhsso/defaults/main.yml"
    -
      name: Set eval_app_host var
      set_fact:
        eval_app_host: "{{ hostvars['EVAL_VARS']['eval_app_host'] }}"
    - include_role:
        name: msbroker
        tasks_from: upgrade
      vars:
        route_suffix: "{{ eval_app_host }}"
        sso_realm: "{{ rhsso_realm }}"

    # data sync update
    - name: Data sync upgrade
      include_role:
        name: datasync

    # Solution Explorer
    - name: Webapp upgrade
      include_role:
        name: webapp
        tasks_from: upgrade
      vars:
        rhsso_openshift_master_config_path: "{{ eval_openshift_master_config_path }}"
        rhsso_namespace: "{{ eval_rhsso_namespace }}"
        openshift_master_url: "{{ hostvars['EVAL_VARS']['openshift_master_url'] }}"
        openshift_asset_url: "{{ hostvars['EVAL_VARS']['openshift_asset_url'] }}"

    - name: SSO upgrade
      include_role:
        name: rhsso
        tasks_from: upgrade

    - name: AMQ Online upgrade
      include_role:
        name: enmasse

    - name: Update image streams
      include_role:
        name: images
        tasks_from: import
      with_items:
        - 3scale
        - apicurito
        - codeready
        - enmasse
        - fuse
        - launcher
        - sso
        - webapp
      loop_control:
        loop_var: images_source_namespace

    # Launcher
    - name: Launcher upgrade
      include_role:
        name: launcher
        tasks_from: upgrade
      when: launcher

    # Monitoring upgrade
    - name: Expose vars
      include_vars: "../../roles/middleware_monitoring_config/defaults/main.yml"

    # Grafana
    - include_role:
        name: middleware_monitoring
        tasks_from: upgrade/grafana

    # Prometheus & Alertmanager
    - include_role:
        name: middleware_monitoring
        tasks_from: upgrade/prometheus

    # Pull the trigger on the monitoring upgrade
    - include_role:
        name: middleware_monitoring
        tasks_from: upgrade/trigger
    # End monitoring upgrade

    - name: Recreate any CRs for alerts to ensure we have the latest
      include_role:
        name: middleware_monitoring_config
        tasks_from: upgrade.yml

    # Backup alerts upgrade
    - include_role:
        name: backup
        tasks_from: upgrade

    # Fuse
    - include_role:
        name: fuse
        tasks_from: upgrade
      vars:
        old_fuse_tag: "application-templates-2.1.fuse-730065-redhat-00002"
        fuse_image_tag: "{{ upgrade_fuse_image_tag }}"

    - include_role:
        name: fuse_managed
        tasks_from: upgrade
      vars:
        fuse_image_tag: "{{ upgrade_fuse_image_tag }}"

    # 3Scale
    - include_role:
        name: 3scale
        tasks_from: upgrade_2.6_to_2.7

    # Need to set 3scale url for fuse 1.8
    - name: Get 3scale dashboard url
      shell: oc get routes -l zync.3scale.net/route-to={{ threescale_route_system_provider }} -o jsonpath='{.items[*].spec.host}' -n {{ threescale_namespace }}
      register: threescale_host_cmd
    
    - name: Setup 3scale integration in Fuse Online
      include_role:
        name: fuse_managed
        tasks_from: config_3scale
      vars:
        threescale_url: "https://{{ threescale_host_cmd.stdout}}"

    # Namespaces
    - include_role:
        name: namespace
        tasks_from: upgrade

    # Heimdall
    - name: Update heimdall resources
      include_role:
        name: "{{ item }}"
        tasks_from: heimdall.yml
      with_items:
      - 3scale
      - apicurito
      - codeready
      - enmasse
      - fuse_managed
      - rhsso
      when: heimdall | default(true) | bool


#Update product version (should always be last)
- import_playbook: "../generate-customisation-inventory.yml"
